# baseURL = 'localhost:1313'
baseURL = 'https://aszfaltozas-architech.hu/'

languageCode = 'hu-Hu'
title = 'ArchiTech Aszfaltozás'
theme = 'pehtheme-hugo'

paginate = 6 # <- Set the desired number of posts per page 
summaryLength = 20 # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Az ArchiTech Aszfaltozás kiváló minőségű útépítési és térburkolási megoldásokat kínál. Tartós, esztétikus aszfaltozás magán- és ipari területekre, gyors kivitelezéssel. Kérjen ajánlatot még ma!'
	mainSections = 'posts'

[author]
	name = 'Dénes - ArchiTech Innovations Kft.'
	bio = 'Az ArchiTech Aszfaltozás kiváló minőségű útépítési és térburkolási megoldásokat kínál. Tartós, esztétikus aszfaltozás magán- és ipari területekre, gyors kivitelezéssel. Kérjen ajánlatot még ma!'
	avatar = '/images/aszfalt.jpg'

[menu] # Menu management
	[[menu.main]]
		name = 'Főoldal'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'Szolgáltatásaink'
		pageRef = '/szolgaltatasaink'
		weight = 14
	[[menu.main]]
		name = 'Rólunk'
		pageRef = '/rolunk'
		weight = 11
	[[menu.main]]
		name = 'Hírek'
		pageRef = '/tags/hírek'
		weight = 25
	[[menu.main]]
		name = 'Kategóriák'
		pageRef = '/categories'
		weight = 21
	[[menu.main]]
		name = 'Tippek'
		pageRef = '/tags'
		weight = 20
		
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [[module.mounts]] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'